// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brkuujubpgctyrdizysu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJya3V1anVicGdjdHlyZGl6eXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTIzMjcsImV4cCI6MjA2MDc4ODMyN30.1oBKMiXzRk163ZbjvVWzoYStIi6S7Apvu7Ulv_5guiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);